/* Author: Abby Nason
 * filename: candidatetables.sql
 * project: Mock Con Database
 * functionality: schema for candidate and prfile tables
 */
 
CREATE TABLE CANDIDATES(
	ID INT PRIMARY KEY NOT NULL,
	NAME VARCHAR(30) NOT NULL
);

CREATE TABLE PROFILES(
	CANDIDATE_ID INT REFERENCES CANDIDATES (ID),
	AGE INT,
	AGE2024 INT,
	RACE CHAR(15),
	BIRTH_PLACE VARCHAR(30),
	CURRENT_RES VARCHAR(30),
	CURRENT_JOB VARCHAR(20),
	SCHOOLING VARCHAR(30),
	FAMILY TEXT,
	PARTY CHAR(5),
	IDEOLOGY INT,
	POSITIONS TEXT,
	PREVIOUS_JOBS TEXT,
	PREVIOUS_PRIMARY_HISTORY TEXT,
	LEGISLATION TEXT,
	ENDORSEMENTS TEXT,
	STATES_VISITED TEXT
);
